name: Run tests on any Push event
# Запуск при любом push-эвенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install requirements
        # Устанавливаем зависимости
        run: |
            pip install -r requirements.txt
            pip install pytest
      - name: Run tests on main.py
        run: pytest test/test_main.py
      - name: Run coverage on main.py
        run: coverage run -m pytest test/test_main.py
      - name: Run tests on tg.py
        run: pytest test/test_tg2.py
      - name: Run coverage on tg.py
        run: coverage run -m pytest test/test_tg2.py    
      - name: Tests report
        run: coverage report
