name: Run tests on any Push event
# Запуск при любом push-эвенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests_main:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install requirements
        # Устанавливаем зависимости
        run: |
            pip install -r requirements.txt
            pip install flake8 pytest
      - name: Run Lint with flake8
        run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests
        run: pytest test/test_main.py
      - name: Run coverage
        run: coverage run -m pytest test/test_main.py
      - name: Tests report
        run: coverage report
  run_tests_tg:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install requirements
        # Устанавливаем зависимости
        run: |
            pip install -r requirements.txt
            pip install pytest
      - name: Run tests
        run: pytest src/test_tg2.py
      - name: Run coverage
        run: coverage run -m pytest src/test_tg2.py
      - name: Tests report
        run: coverage report
